### ISSUE TITLE
Fennec: Problem with browserleaks.com

### ISSUE THREAD

**Issue by gallegonovato** [CHEF-KOCH/FFCK#30]
Good afternoon: Thank you very much for your new user.js for fennec. The web https://browserleaks.com shows all the values ​​and ublock filters. You could also make it hide in these sections: https://browserleaks.com/javascript https://browserleaks.com/webrtc https://browserleaks.com/canvas https://browserleaks.com/features https://browserleaks.com/proxy

 And that does not show HTML5 Canvas Protection abroad (html5, etc.). and Adblock Detection (ublock filters). Because I understand that if it comes out it shows it abroad. 

a hug and thanks for your time

 pd: the user.js file for Fenix ​​or Icecat ?. You would have to rename the user-android.js to user.js so that it detects it better.

**Comment by CHEF-KOCH** [comment]
1.) You can't compare Fennec with a Desktop version. Which means the leak test is more inefficient under Android, no matter what it shows, due to the fact that the app as well the upper layer runs isolated.
2.) Fennec from F-Droid repository removed all "critical" features not only google exclusive ones.
3.) I do not support Icecat.
4.) We already have a "user.js" (for Desktop) I simply renamed it to get a better overview, I have no intention to change it.


The Simplest method on android is to work with ADB, make sure your .js file is named user.js and that `*default` is corresponding to your actual profile name (e.g. `/data/data/org.mozilla.fennec_fdroid/files/mozilla/xxxxx.default` while xxxxx is the random ID to your profile!).

```bash
adb root
adb push user.js /data/data/org.mozilla.fennec_fdroid/files/mozilla/*default/
adb shell
# cd /data/data/org.mozilla.fennec_fdroid/files/mozilla/*default/
# ls -l
```

When you work with uBlock the browserleaks.com test is pointless, you simply can disable JavaScript per-site basis, check if the page works or not and then unblock it if it causes problems. However, I give you the point that this (once a website got unblocked) you are still possible expose data, but WebRTC is no longer a problem since Fennec does not leak WebRTC by itself.

I check the current toggles ASAP but there aren't many compared to desktop because as said, Android works different.

**Comment by CHEF-KOCH** [comment]
Please test https://github.com/CHEF-KOCH/FFCK/commit/786f0c3a2f8308b379013c6db9af4fd47a7af78e

**Comment by gallegonovato** [comment]
Good afternoon: Thank you very much for your help, that I have to modify those values ​​in the android user (that is, in user-android.js). or change the one in red to true a hug and thanks for your help

**Comment by CHEF-KOCH** [comment]
The upgrade procedure is the same, you override the current user.js file with the updated one.

**Comment by gallegonovato** [comment]
good afternoon: It would be this link: https://github.com/CHEF-KOCH/FFCK/blob/786f0c3a2f8308b379013c6db9af4fd47a7af78e/user.js/user-android.js? But the entry dom.event.clipboardevents.enabled that appears in red at https://github.com/CHEF-KOCH/FFCK/commit/786f0c3a2f8308b379013c6db9af4fd47a7af78e still appears. Don't I have to delete that entry? a hug and sorry for being so clumsy

**Comment by CHEF-KOCH** [comment]
[Reverting about:config settings to default](https://github.com/CHEF-KOCH/FFCK/issues/28).

**Comment by gallegonovato** [comment]
good afternoon: 

But on this link: https://github.com/CHEF-KOCH/FFCK/blob/786f0c3a2f8308b379013c6db9af4fd47a7af78e/user.js/user-android.js; the entry dom.event.clipboardevents.enabled that appears in red at https://github.com/CHEF-KOCH/FFCK/commit/786f0c3a2f8308b379013c6db9af4fd47a7af78e is still going on line 347 and if I use the search engine on the same link (RAW) still is. But if yes to not appear in front // user_pref is it already deleted? 

a hug and sorry for being so clumsy and in zero programming

**Comment by CHEF-KOCH** [comment]
I checked browserleaks as well as panopticlick, both depending on `privacy.resistfingerprinting` which is problematic on Android, or in other words there is nothing I can do here. Installing desktop addons on Android is also no solution, they simply don't work (no permissions) or you need root/specific Firefox builds or crashes (slowing-down) the Browser. 

I don't see how this is useful and that's why I'm closing it.
