### ISSUE TITLE
Note about ToDo: javascript is omnipotent.

### ISSUE THREAD

**Issue by Atavic** [CHEF-KOCH/FFCK#6]
[Quote](https://github.com/CHEF-KOCH/FFCK#todo):

> DOM is not evil, JavaScript is, the abuse may only affects several test pages - *we need to mention* and verify it.

With javascript enabled, any page containing a JS script can access
```resource://gre/modules/``` which contains [JavaScript Code Modules (JSM)](https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules) that run with system privileges if called from inline frames:

> The system principal passes all security checks.

https://developer.mozilla.org/en-US/docs/Mozilla/Gecko/Script_security#Principals

> Frame scripts run with system privileges and have access to the Components object, enabling them to use XPCOM objects and JSMs. 

https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Multiprocess_Firefox/Limitations_of_frame_scripts

**Comment by CHEF-KOCH** [comment]
1.) On Windows, JavaScript can be blocked by disabling WSH which also blocks, VBS, VBE and Windows Script files. Once Windows Script Host is disabled you can execute whatever you want it doesn't do anything. Keep in mind that modern Windows also coming with AV programs which probably already detecting dangerous behavior. 
2.) [JavaScript already runs isolated in any modern browser](https://www.springer.com/cda/content/document/cda_downloaddocument/9783319430041-c2.pdf?SGWID=0-0-45-1585376-p180163317). This means if there is no HTML <script> tag it can't get access to dangerous places, and even with the tag JavaScript execute them inside the web-page’s JavaScript execution environment only.
3.) Your scenario doesn't cover Chrome/Chromium. I'm aware of it that we#re here in a Firefox-only project/situation but the argumentation here is that Javascript is limited with different Browser engines. 
4.) None of your provided links says anything about "system privileges", it moreover says the opposite "isolated from the local system through a content security sandbox". There is no attack scenario here.  I'm not sure if something is confirmed here and I wouldn't say JavaScript is omnipotent because there some [alternatives](https://github.com/jashkenas/coffeescript/wiki/List-of-languages-that-compile-to-JS), JavaScript is most used because it's feature-rich but this doesn't mean some pages not using other stuff (if supported by Firefox [othjer browsers]). 


## Real problem 
The real problem is that it's compiled by the browser, and that means it works in a very different way depending on the client. Not only is the actual DOM different depending on the browser, but there's a massive difference in performance and layout.

Personally, I think Javascript isn't so _bad_ if you start thinking about DOM model and how would one work with it. Many things that are messy with JS are the result of the way DOM model works. However, the thing is that since JavaScript works in every Browser it's really powerful and this brings us in the position to choose to use it while you like to use it "for good" stuff like e.g. encryption etc or to abuse it "for evil" reasons. Changing this situation would end up in another browser war. I'm not sure if you can blame something if the website developer chooses insecure stuff in order to provide certain things. 

Research:
* https://walkercoderanger.com/blog/2014/02/javascript-minefield/
* https://www.w3.org/wiki/JavaScript_best_practices
* https://glebbahmutov.com/blog/disable-inline-javascript-for-security/
* https://www.torproject.org/docs/faq.html.en#TBBJavaScriptEnabled

Real-World example:
* https://vimeo.com/99599725 (via Cross-site scripting (XSS) attack)

Papers:
* https://www.eecis.udel.edu/~hnw/paper/tweb.pdf
* http://www.ccs.neu.edu/home/arshad/publications/ndss2017jslibs.pdf
